name: Lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    name: xmtp-js-sdk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.10.0
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm lint
