name: Lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Setup buf build
        uses: bufbuild/buf-setup-action@v0.6.0
      - run: npm ci
      - run: npm run lint
