name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: xmtp-js-sdk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: npm install
      - run: npm run test
